# -*- coding: utf-8 -*-
"""
Created on Wed Feb 19 16:54:18 2020

Data I/O.

@author: zdang2
"""
import json

def read_sfm(file_name, path):
    """
    Reads SfM results generated by openMVG and parse the data.
    Input: filename, path.
    Output: metadata - views, internal parameters - intrinsics,
            external parameters - extrinsics, 3-D point coordinates - sturcture
            control points
    """
    file = path + file_name
    with open(file, 'r') as openfile:
        sfm = json.load(openfile)

    control_points = sfm['control_points']
    extrinsics = sfm['extrinsics']
    intrinsics = sfm['intrinsics']
    root_path = sfm['root_path']
    coords_3d = sfm['structure']
    views_meta = sfm['views']

    # Formatting
    intrinsics = intrinsics[0]['value']
    
    for i in range(0, len(extrinsics)):
        extrinsics[i] = extrinsics[i]['value']
    
    for i in range(0, len(views_meta)):
        views_meta[i] = views_meta[i]['value']
        
    for i in range(0, len(coords_3d)):
        coords_3d[i] = coords_3d[i]['value']
#    
    return root_path, extrinsics, intrinsics, coords_3d, views_meta, control_points